### ISSUE TITLE
Calculate LFP

### ISSUE THREAD

**Issue by latimerb** [AllenInstitute/bmtk#77]
Has anyone made a function to calculate the local field potential (LFP)? I will write it if not. We use the line-source approximation from 

Schomburg, E. W., Anastassiou, C. A., Buzsaki, G., & Koch, C. (2012). The Spiking Component of Oscillatory Extracellular Potentials in the Rat Hippocampus. Journal of Neuroscience, 32(34), 11798–11811.

**Comment by kaeldai** [comment]
BioNet does have the ability to calculate the LFP. [Here is an example](https://github.com/AllenInstitute/bmtk/blob/develop/docs/examples/bio_450cells_exact/config.json#L70) of how to edit the the config file to have a simulation record from an extracellular electrode. You'll need to change the "cells" to the list of ids you want to record from (or you can put a dictionary of lookup values, eg {'model_type': 'biophysical'}). Also make sure to adjust the **linear_electrode.csv** file so that the coordinates of the extracellular channels are close enough to the cells. If successful it will create an **ecp.h5** file with the [following format](https://github.com/AllenInstitute/sonata/blob/master/docs/SONATA_DEVELOPER_GUIDE.md#extracellular-report).

A couple of things to keep in mind when running a simulation with ecp:
* It will record from cells with full morphologies and even single-somas, but ignore intfire type cells.
* It will drastically slow down the simulation, expect the simulations to take ~5 times as long.
* The **ecp.h5** file contains, at each channel specified in the csv file, the summed contributions of each cell. The individual contributions of each cell is saved under the _contributions_dir_ directory. But if you network is very large you may want to remove _contributions_dir_ or set the value to _null_ because it can get really large.

Hope this is what you're looking for?

**Comment by latimerb** [comment]
@kaeldai Yes, this is great. I'll check it out.
